standaloneAddContents({
  code: "castor_2020",
  title: "مسابقات ببراس ۲۰۲۰",
  folder: "2020/",
  language: "fa",
  difficulties: ["easy", "medium", "hard"],
  tasks: [
     { code: "2020-CH-07-trade",
       title: "معاملات" },
     { code: "2020-FR-01-play-music",
       title: "کنسرت ببراس" },
     { code: "2020-FR-02-split-flowers",
       title: "قارچ‌ها" },
     { code: "2020-FR-03-waiting-room",
       title: "اتاق انتظار" },
     { code: "2020-FR-04-joke-propagation",
       title: "فکر بکر" },
     { code: "2020-FR-05-css",
       title: "قالب بندی" },
     { code: "2020-FR-06-overlap-rectangles",
       title: "رنگ کردن جدول" },
     { code: "2020-FR-07-tool-deadlock",
       title: "ساخت هواپیما" },
     { code: "2020-IE-07-pollution",
       title: "لوله آلوده" },
     { code: "2020-PT-03-creating-numbers",
       title: "پرتاب توپ" },
     { code: "2020-FR-10-reorder",
       title: "برعکس‌کردن" },
     { code: "2020-FR-09-loops",
       title: "برنامه‌ریزی ربات" }
    ]
  });